### ISSUE TITLE
run_elastix main branch doesn't support -ap and -bp options yet

### ISSUE THREAD

**Issue by tkclam** [NeLy-EPFL/DeMotion5D#2]
It looks like [2_run_elastix.sh](https://github.com/NeLy-EPFL/DeMotion5D/blob/085a395c33b3e738b2f35eada7db42a050a27c1e/2_run_elastix.sh) uses -ap and -bp options that aren't supported by the main branch of [run_elastix](https://github.com/htem/run_elastix/blob/ddc1ce3e52c1121d9e3526eddcd01db685a3bb0a/run_elastix) yet. I guess there are some unpushed changes?

**Comment by jasper-tms** [comment]
Thanks for the reminder! Pushed in [version 2.0.0](https://github.com/htem/run_elastix/releases/tag/v2.0.0), specifically commit  htem/run_elastix@224b3d3
